package io.flowcatalyst.platform.shared.openapi;

import tools.jackson.databind.JsonNode;

import java.net.InetAddress;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.UnknownHostException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

/// The recursive value-against-schema engine behind [SchemaValidation] (Go:
/// huma `validate.go` `Validate` / `handleMapString`, request direction
/// only — this platform never validates a *response*, so `ModeReadFromServer`
/// and `writeOnly` never come up).
///
/// ## Implemented keywords
///
/// Exactly the set `docs/process/briefs/2026-09-05-request-schema-validation.md`
/// names, confirmed against the committed lockfile with a one-off script
/// (2026-09-05: the lockfile itself currently uses only `$ref`, `type`,
/// `required`, `properties`, `items`, `additionalProperties`, `format`,
/// `minimum`, `enum` and `readOnly` — the rest are implemented ahead of use
/// so a lockfile bump that starts using them does not silently validate
/// nothing):
///
/// `type`, `required`, `properties`, `items`, `enum`, `format`, `minLength`,
/// `maxLength`, `minimum`, `maximum`, `pattern`, `additionalProperties`,
/// `$ref`, `nullable`.
///
/// Two more keys are *recognised* but carry no validation semantics of their
/// own: `readOnly` (exempts an absent property from its own required-ness in
/// the write direction — spec §2; a *present* readOnly value is still
/// type-checked, matching Go's `handleMapString`, not literally "ignored")
/// and `writeOnly` (only matters for `ModeReadFromServer`, so it is inert
/// here; kept recognised because a lockfile bump could add one). Everything
/// else annotation-only (`description`, `examples`, `example`, `title`,
/// `default`, `deprecated`) is recognised and skipped. Any OTHER key found on
/// a schema node during the startup walk — `multipleOf`, `minItems`,
/// `maxItems`, `uniqueItems`, `minProperties`, `maxProperties`,
/// `dependentRequired`, `oneOf`/`anyOf`/`allOf`, `exclusiveMinimum`/`Maximum`,
/// `discriminator`, `patternProperties`, `const`, `contentEncoding`… — fails
/// the server at startup ([SchemaValidation#build]) rather than silently
/// validating nothing for it.
///
/// ## Corrections to the written spec (verified against
/// `huma/v2@v2.38.0` source, module-cached read-only under
/// `~/go/pkg/mod/github.com/danielgtaylor/huma`, and against
/// `flowcatalyst-go/internal/platform/shared/httpcompat/httpcompat.go`):
///
///   - **`additionalProperties` is NOT `false` on every model.** Go's own
///     `httpcompat.RelaxRequestBodies` (doc comment: "the #1 recurring parity
///     bug class") flips every TOP-LEVEL request-body schema's
///     `additionalProperties` to `true` after generation, and the *committed
///     lockfile already reflects that* — confirmed by survey: every
///     `Create*Request` / `Update*Request` in `openapi.lock.json` is `true`;
///     only schemas nested inside a bulk/sync array (`Sync*InputRequest`) are
///     `false`. This validator reads the keyword verbatim per schema node —
///     it does not hard-code a direction — which reproduces this asymmetry
///     for free.
///   - **A missing required QUERY parameter is not the object-shaped
///     message.** Go's `huma.go` request-binding loop (not `validate.go`)
///     emits `"required query parameter is missing"` /
///     `"required path parameter is missing"` at `<in>.<name>` with
///     `value: ""` — never the generic `expected required property … to be
///     present` the spec doc describes.
///   - **Property/required ordering is a single alphabetically-sorted pass,
///     not "required first, then properties."** `schema.go`
///     `PrecomputeMessages` builds `propertyNames` by iterating the
///     `Properties` map and `sort.Strings`-ing it; `handleMapString` walks
///     that ONE list, emitting a required-missing error or recursing into a
///     present value at each name in turn — there is no separate
///     required-first pass. This lockfile is generated by Go's
///     `encoding/json`, which marshals map keys already sorted, so
///     preserving each schema's own JSON `properties` key order (Jackson
///     keeps document order) reproduces Go's real iteration order without
///     re-sorting.
final class SchemaValidator {

    private SchemaValidator() {
    }

    // ── keyword implementations ─────────────────────────────────────────

    private static final Set<String> VALIDATION_KEYWORDS = Set.of(
            "type", "required", "properties", "items", "enum", "format",
            "minLength", "maxLength", "minimum", "maximum", "pattern",
            "additionalProperties", "$ref", "nullable");

    /// Recognised but inert for request validation — see the class doc.
    private static final Set<String> ANNOTATION_KEYWORDS = Set.of(
            "description", "examples", "example", "title", "default", "deprecated",
            "readOnly", "writeOnly");

    /// Walks every schema node reachable from `schema` (properties, array
    /// items, a schema-valued `additionalProperties`, `$ref` targets) and
    /// throws if any carries a key outside [#VALIDATION_KEYWORDS] ∪
    /// [#ANNOTATION_KEYWORDS]. `visitedRefs` is shared across the whole
    /// startup build (see [SchemaValidation#build]) so a component schema
    /// reached from many operations is only checked once, and a self- or
    /// mutually-referencing `$ref` cycle terminates instead of recursing
    /// forever.
    static void checkKeywords(Lockfile lockfile, JsonNode schema, Set<String> visitedRefs) {
        if (schema == null || schema.isMissingNode() || !schema.isObject()) {
            return;
        }
        if (schema.has("$ref")) {
            var ref = schema.path("$ref").stringValue();
            if (!visitedRefs.add(ref)) {
                return;
            }
            checkKeywords(lockfile, lockfile.resolveRef(schema), visitedRefs);
            return;
        }
        for (var entry : schema.properties()) {
            var key = entry.getKey();
            if (!VALIDATION_KEYWORDS.contains(key) && !ANNOTATION_KEYWORDS.contains(key)) {
                throw new IllegalStateException(
                        "unimplemented schema keyword \"" + key + "\" — extend SchemaValidator "
                                + "(or add it to the recognised-but-inert annotation set if it carries no validation semantics)");
            }
        }
        if (schema.has("properties")) {
            for (var entry : schema.path("properties").properties()) {
                checkKeywords(lockfile, entry.getValue(), visitedRefs);
            }
        }
        if (schema.has("items")) {
            checkKeywords(lockfile, schema.path("items"), visitedRefs);
        }
        if (schema.path("additionalProperties").isObject()) {
            checkKeywords(lockfile, schema.path("additionalProperties"), visitedRefs);
        }
    }

    // ── request-time validation ─────────────────────────────────────────

    /// Validates `value` (a parsed JSON body, sub-object, array element, or a
    /// coerced query/path parameter value) against `schema`, appending one
    /// `{location, message, value?}` map per failure to `errors` — mirrors
    /// Go's `Validate`: every failure is recorded, nothing throws on the
    /// first one, and a full type mismatch skips the type-specific
    /// sub-checks (Go returns immediately) while a sub-check failure within
    /// a matching type does not (minLength failing does not skip pattern).
    static void validateValue(Lockfile lockfile, JsonNode schema, String location, JsonNode value, List<Map<String, Object>> errors) {
        var s = lockfile.resolveRef(schema);
        if (s.path("nullable").asBoolean(false) && value.isNull()) {
            return;
        }
        if (!s.has("type")) {
            checkEnum(s, location, value, errors);
            return;
        }
        var type = s.path("type").stringValue();
        switch (type) {
            case "boolean" -> {
                if (!value.isBoolean()) {
                    addError(errors, location, ValidationMessages.expectedBoolean(), value);
                    return;
                }
            }
            case "integer", "number" -> {
                if (!value.isNumber()) {
                    addError(errors, location, "integer".equals(type) ? ValidationMessages.expectedInteger() : ValidationMessages.expectedNumber(), value);
                    return;
                }
                var num = value.numberValue().doubleValue();
                if ("integer".equals(type) && num != Math.rint(num)) {
                    addError(errors, location, ValidationMessages.expectedInteger(), value);
                }
                if (s.has("minimum")) {
                    var min = s.path("minimum").numberValue().doubleValue();
                    if (num < min) addError(errors, location, ValidationMessages.minimum(min), value);
                }
                if (s.has("maximum")) {
                    var max = s.path("maximum").numberValue().doubleValue();
                    if (num > max) addError(errors, location, ValidationMessages.maximum(max), value);
                }
            }
            case "string" -> {
                if (!value.isString()) {
                    addError(errors, location, ValidationMessages.expectedString(), value);
                    return;
                }
                var str = value.stringValue();
                var length = str.codePointCount(0, str.length());
                if (s.has("minLength") && length < s.path("minLength").asInt()) {
                    addError(errors, location, ValidationMessages.minLength(s.path("minLength").asInt()), value);
                }
                if (s.has("maxLength") && length > s.path("maxLength").asInt()) {
                    addError(errors, location, ValidationMessages.maxLength(s.path("maxLength").asInt()), value);
                }
                if (s.has("pattern")) {
                    var pattern = s.path("pattern").stringValue();
                    if (!Pattern.compile(pattern).matcher(str).find()) {
                        addError(errors, location, ValidationMessages.matchPattern(pattern), value);
                    }
                }
                if (s.has("format")) {
                    validateFormat(str, s.path("format").stringValue(), location, value, errors);
                }
            }
            case "array" -> {
                if (!value.isArray()) {
                    addError(errors, location, ValidationMessages.expectedArray(), value);
                    return;
                }
                var items = s.path("items");
                for (int i = 0; i < value.size(); i++) {
                    validateValue(lockfile, items, location + "[" + i + "]", value.get(i), errors);
                }
            }
            case "object" -> {
                if (!value.isObject()) {
                    addError(errors, location, ValidationMessages.expectedObject(), value);
                    return;
                }
                validateObject(lockfile, s, location, value, errors);
            }
            default -> throw new IllegalStateException("unimplemented schema type: " + type);
        }
        checkEnum(s, location, value, errors);
    }

    /// `required` first-missed-then-present-and-recurse pass over
    /// `schema.properties`, in the schema's own key order (see class doc:
    /// this already IS Go's alphabetical order, because the lockfile was
    /// dumped by `encoding/json`), then the `additionalProperties` pass over
    /// the ACTUAL body's keys.
    private static void validateObject(Lockfile lockfile, JsonNode schema, String location, JsonNode value, List<Map<String, Object>> errors) {
        var properties = schema.path("properties");
        if (properties.isObject()) {
            for (var entry : properties.properties()) {
                var name = entry.getKey();
                var propSchema = entry.getValue();
                var actual = findCaseInsensitive(value, name);
                var required = isRequired(schema, name);
                if (actual == null) {
                    var readOnly = lockfile.resolveRef(propSchema).path("readOnly").asBoolean(false);
                    if (required && !readOnly) {
                        addError(errors, location, ValidationMessages.requiredProperty(name), value);
                    }
                    continue;
                }
                var nullable = lockfile.resolveRef(propSchema).path("nullable").asBoolean(false);
                if (actual.isNull() && (!required || nullable)) {
                    continue;
                }
                validateValue(lockfile, propSchema, location + "." + name, actual, errors);
            }
        }

        var additional = schema.path("additionalProperties");
        if (additional.isBoolean() && !additional.booleanValue()) {
            for (var entry : value.properties()) {
                if (!hasCaseInsensitive(properties, entry.getKey())) {
                    addError(errors, location + "." + entry.getKey(), ValidationMessages.unexpectedProperty(), value);
                }
            }
        } else if (additional.isObject()) {
            for (var entry : value.properties()) {
                if (!hasCaseInsensitive(properties, entry.getKey())) {
                    validateValue(lockfile, additional, location + "." + entry.getKey(), entry.getValue(), errors);
                }
            }
        }
        // additionalProperties == true (or absent — JSON Schema defaults an
        // absent additionalProperties to true): no check, matching Go, whose
        // `AdditionalProperties.(bool)` type-switch only fires the reject
        // branch when the value is the boolean `false`.
    }

    private static boolean isRequired(JsonNode schema, String name) {
        for (var r : schema.path("required")) {
            if (r.isString() && name.equals(r.stringValue())) {
                return true;
            }
        }
        return false;
    }

    /// huma matches property names case-insensitively when
    /// `ValidateStrictCasing` is false (the platform's default; spec §2) —
    /// reads under the lockfile's own spelling so the caller always
    /// recurses with the schema-declared name in scope, even if the wire
    /// sent a case variant.
    private static JsonNode findCaseInsensitive(JsonNode object, String name) {
        if (object.has(name)) {
            return object.path(name);
        }
        for (var entry : object.properties()) {
            if (entry.getKey().equalsIgnoreCase(name)) {
                return entry.getValue();
            }
        }
        return null;
    }

    private static boolean hasCaseInsensitive(JsonNode properties, String name) {
        if (properties.has(name)) {
            return true;
        }
        for (var entry : properties.properties()) {
            if (entry.getKey().equalsIgnoreCase(name)) {
                return true;
            }
        }
        return false;
    }

    private static void checkEnum(JsonNode schema, String location, JsonNode value, List<Map<String, Object>> errors) {
        if (!schema.has("enum")) {
            return;
        }
        var enumNode = schema.path("enum");
        for (var candidate : enumNode) {
            if (candidate.equals(value)) {
                return;
            }
        }
        var rendered = new ArrayList<String>();
        for (var candidate : enumNode) {
            rendered.add(goFormatScalar(candidate));
        }
        addError(errors, location, ValidationMessages.expectedOneOf(rendered), value);
    }

    private static String goFormatScalar(JsonNode n) {
        if (n.isString()) return n.stringValue();
        if (n.isBoolean()) return String.valueOf(n.booleanValue());
        if (n.isNumber()) return GoNumbers.format(n.numberValue().doubleValue());
        return n.toString();
    }

    private static void addError(List<Map<String, Object>> errors, String location, String message, JsonNode value) {
        var e = new LinkedHashMap<String, Object>();
        e.put("location", location);
        e.put("message", message);
        // Go omits `value` only when the underlying value is a Go `nil` — an
        // explicit JSON `null` is exactly that case (spec §1's closing note).
        if (value != null && !value.isNull()) {
            e.put("value", toPlainValue(value));
        }
        errors.add(e);
    }

    /// Converts a [JsonNode] into the plain `String`/`Number`/`Boolean`/`Map`/
    /// `List` shape [io.flowcatalyst.platform.shared.json.Json.MAPPER] can
    /// re-serialise the same way it would have serialised the request body
    /// itself.
    static Object toPlainValue(JsonNode node) {
        if (node.isObject()) {
            var m = new LinkedHashMap<String, Object>();
            for (var e : node.properties()) {
                m.put(e.getKey(), toPlainValue(e.getValue()));
            }
            return m;
        }
        if (node.isArray()) {
            var l = new ArrayList<Object>();
            for (var item : node) {
                l.add(toPlainValue(item));
            }
            return l;
        }
        if (node.isString()) return node.stringValue();
        if (node.isBoolean()) return node.booleanValue();
        if (node.isNumber()) return node.numberValue();
        return null;
    }

    // ── format (Go `validate.go` `validateFormat` — TypeString only; a
    //    numeric schema's `format` (`int32`/`int64` in this lockfile) is
    //    never inspected by Go either, so it is simply never reached here) ──

    private static void validateFormat(String str, String format, String location, JsonNode value, List<Map<String, Object>> errors) {
        switch (format) {
            case "date-time" -> {
                if (!isRfc3339DateTime(str)) addError(errors, location, ValidationMessages.expectedRfc3339DateTime(), value);
            }
            case "date" -> {
                if (!isRfc3339Date(str)) addError(errors, location, ValidationMessages.expectedRfc3339Date(), value);
            }
            case "time" -> {
                if (!isRfc3339Time(str)) addError(errors, location, ValidationMessages.expectedRfc3339Time(), value);
            }
            case "email" -> {
                var detail = emailError(str);
                if (detail != null) addError(errors, location, ValidationMessages.expectedRfc5322Email(detail), value);
            }
            case "uri" -> {
                var detail = uriError(str);
                if (detail != null) addError(errors, location, ValidationMessages.expectedRfc3986Uri(detail), value);
            }
            case "uuid" -> {
                var detail = uuidError(str);
                if (detail != null) addError(errors, location, ValidationMessages.expectedRfc4122Uuid(detail), value);
            }
            case "hostname" -> {
                if (!isValidHostname(str)) addError(errors, location, ValidationMessages.expectedRfc5890Hostname(), value);
            }
            case "ipv4" -> {
                if (!isIpv4(str)) addError(errors, location, ValidationMessages.expectedRfc2673Ipv4(), value);
            }
            case "ipv6" -> {
                if (!isIpv6(str)) addError(errors, location, ValidationMessages.expectedRfc2373Ipv6(), value);
            }
            default -> {
                // huma's own `validateFormat` switch has no default case either: an
                // unrecognised format string is documentation only, never a runtime
                // check. Not implemented here for the same reason and on the same
                // authority — matching Go exactly, not an omission.
            }
        }
    }

    private static boolean isRfc3339DateTime(String s) {
        try {
            OffsetDateTime.parse(s);
            return true;
        } catch (DateTimeParseException e) {
            return false;
        }
    }

    private static boolean isRfc3339Date(String s) {
        try {
            LocalDate.parse(s);
            return true;
        } catch (DateTimeParseException e) {
            return false;
        }
    }

    private static boolean isRfc3339Time(String s) {
        try {
            OffsetTime.parse(s);
            return true;
        } catch (DateTimeParseException e1) {
            try {
                LocalTime.parse(s);
                return true;
            } catch (DateTimeParseException e2) {
                return false;
            }
        }
    }

    /// Not exercised by the live lockfile or the parity corpus (no
    /// `format: email` on any request-reachable schema, 2026-09-05 survey) —
    /// a dependency-free approximation of `net/mail.ParseAddress`'s
    /// accept/reject boundary is enough; spec §1 treats the detail text as a
    /// loose comparison, only the message prefix is contractual.
    private static final Pattern EMAIL_PATTERN = Pattern.compile("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$");

    private static String emailError(String s) {
        return EMAIL_PATTERN.matcher(s).matches() ? null : "invalid email address";
    }

    /// `format: uri` DOES appear live (`$schema`, every model's readOnly
    /// self-link) — `java.net.URI` is stricter than Go's very permissive
    /// `net/url.Parse`, but the only live user is a server-generated,
    /// read-only field a client essentially never sends.
    private static String uriError(String s) {
        try {
            new URI(s);
            return null;
        } catch (URISyntaxException e) {
            return e.getReason() == null ? "invalid uri" : e.getReason();
        }
    }

    private static final Pattern UUID_PATTERN =
            Pattern.compile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

    private static String uuidError(String s) {
        return UUID_PATTERN.matcher(s).matches() ? null : "invalid UUID format";
    }

    /// Verbatim port of huma's `rxHostname` plus its length guard.
    private static final Pattern HOSTNAME_PATTERN = Pattern.compile(
            "^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])(\\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9]))*$");

    private static boolean isValidHostname(String s) {
        return s.length() < 256 && HOSTNAME_PATTERN.matcher(s).matches();
    }

    private static boolean isIpv4(String s) {
        var parts = s.split("\\.", -1);
        if (parts.length != 4) return false;
        for (var p : parts) {
            if (p.isEmpty() || p.length() > 3 || !p.chars().allMatch(Character::isDigit)) return false;
            if (Integer.parseInt(p) > 255) return false;
        }
        return true;
    }

    /// `InetAddress.getByName` never performs a DNS lookup for a literal
    /// address (only for an actual hostname), so this is safe without a
    /// dependency; not exercised live (no `format: ipv6` in the lockfile).
    private static boolean isIpv6(String s) {
        if (!s.contains(":")) return false;
        try {
            return InetAddress.getByName(s) instanceof java.net.Inet6Address;
        } catch (UnknownHostException e) {
            return false;
        }
    }
}
